### PR TITLE
Frontend connection

### PR DESCRIPTION
**Pull request by marwa93nezar**

### CODE REVIEW

**Comment by Eli3336** [comment]
I'm a bit confused as to why is the pull request for the main branch instead of dev. If you could explain a bit?

**Comment by marwa93nezar** [comment]
I tried to push it to the frontend branch!

**Comment by Eli3336** [comment]
There is no frontend branch. Only main and dev. We need to make pull requests to dev and when a whole functionality or sprint is done we merge dev into main.

**Comment by Xbey25** [comment]
Closed as it is not for the main

**Pull request closed without merging**
